---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-secret
  namespace: default
spec:
  encryptedData:
    password: AgB8CSVmBo4zLnBMWAIAFGRy723da3y3RVHG+2wbzrUa8bURBtCtTyjp6ZbXeRNSdM8xnm1djYl9uFZweUlVR3xJFTxTcB/c8SRvrfHH/4OL5lgkYY6LyKwqgpvpvxugFrUgEYZKzmh3LcbtfIPhnds+6NEm8fGg3Nx8nvTjDOa8T97xFu+4MMZPQh7th/hzisWUHtMBfaSZCosdsKX3sYfEr4uw2dGw/0HPvUENmuFDnoKqySwyqmLDB0C9hEhJYEHZdyUjGYvoE+9RytHlEwheg0ZiM0xP2wfnWBh/+5Ycn34gk6AFz3Dnf5qhsJ6Vm1SmydLV3fAUEZWCxbjDbMJ6PXnVJWeCHafJfkpieBvI0WyzIVZkmQsk7RbtJJVhmvWk8AVqrAZ7iY3yqq9MS5zh5cilQ9UoSmFha6ae8vhPPrMfXSVNWfHuAUfPKGWh+wSt8mvY6nnYSejeX+rKThEsok7PPk4bvul12bf67lodmkoeg5bpedq3HsxVIiKUYP5p6kuKk56Kan3m3IO7OtM7seQYSf+8KC1ueYcvkBXI5QVNrSgF3NAu85GfAEChFVM7+Co5eKtSKs8mrPYgTHinJYt2RkBtxJcFhhsgJhPYakgaJRsHv3LXrXRNSA17AyaNM+N/sql9NnUftB9CLaKyRqDjv67z2ta7mCnJqc1yHfP0QcXSR4PNOdWFYkPDopX2JLKDe0uMgGOrDRi/Rg==
  template:
    metadata:
      name: demo-secret
      namespace: default
