---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenkins-admin
  namespace: jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    jenkins-admin-password: AgBGIAZzLJLVnHHSEUfeuo/5y+aZ55DO8MMym1zl5r4nJy+5JfZmcri5PRW8PhsVj+TFuCaBGoVSfM1C08rDftfvE5SFtRfsglhGKgIv0OTse2huUZI4WszKKSmPe4FyRn4E2iJR6O/nA5us0tyP8f/Pb0q6jZJMtW8pvOXyGPcucey8z6yrzQcxxt2Y7RPSpz3RG8K82cEkvRnpH1HnUhJVU/cQmIb3pxZgD2k/rx0eThE23jQ4KxeaNeh9Xjn15w0IvCuiNyHmkMKEaARYEbP6cewZGCr2dW/K/Ys0AfRAFMTPry3VJ73QGkx+PWhGREBn4zGP8fPmvenVOE6dIq6UEnSSswYKjn+3+mY54Z0DJ43gLlEi7tZAoTu6EH71wwFw9BOeW5B0AsXj1By3M1yDggmN09J1h2I97FtYpWhb1frafINs4AWFnG1tKSKlSnJI1Me45kKOIMN0kbR1TR7We/h+Qj8HYmhtl9tcw9siRR8aWJdvDyUsWgzi28GmltJe4MOxs2aOgHYkV23gRf8Xsm68D3NFleDHMYjWAfCDQEqgRuOHqQ1LMFYnLIzldKtR6pBbD5acdTlNlfwIQILtgGjJGSjhd2Qs6iWdOZkU/YdMj4/Ou/XOr376pQpqJTwu5M7N2NgU/lj2ysnBMNConbB8mBBzsqYjyot221Nc6fY1is/XrPA91jbrlMJZxYPmISrHpFc6/DjRmMrli03gceMZnwG2gC0=
    jenkins-admin-user: AgAzCooBJsUTbsfUgFPdtDKdmjfN+V1FHLWWCyfCrpX8f/ISg99yEvaQmdt/1oxyQ4n7uYCnkPYEDZ8cR8cN8p61+L1NcOLVIZJUWUf7YCnnhVhQFWkGFM5cdbi7wGFl6Rut93ymFOS7eil9BvxSCdsv4hWlvF8rGPjVQ9TjVS/yi3GWRBCl6I7LAbCg4lgQBIt4WaDGPr+Vevtqd01uVBJLBjRg2MKkGRhjCEtysplp58um+DcflBLxgjOM64lB8T8ytVwMEhLz/nZo/gFiLufJVy3lMrAVHGPBGQs9KgrgfbeYrqtitlrcJjfBa0rZgPz65WKYTlbphDVH8IyKtga/sFeAA8a/8J91mq8ykQIybwx5AT70Cyp+qaNhOOtsYsZOxkXc+wyuw9bMxfho+7DMsPbC/lvSisFAkETH0azKRO1EYyctEpPPpnFkqMgbupGxGoIDupU+BV4nsmk/LzQLGEZAa0Gijtb1q+tALRNeUxmunx+T97TYttmKJ2hHZeyV6PqskaMSWMVWwuDfXLv2U/IDsFO2TMOJRo6bhamNmTvpfFtNOzvsRPRjmvI7KrTBGjKOJugvPRYh+bX7hWd6gXc/G3GtwrRbEWjpmbYgOPC1v9w7wJQ21MKnOcplO7oOSiHdQ+zheBzgxdGk1psxHuji9N+xC8BHkaWCEBdH5bRpt3nSvCYL1CMlpzRu5PHmam7/zQ==
  template:
    metadata:
      name: jenkins-admin
      namespace: jenkins
