USER-SUPPLIED VALUES:
controller:
  metrics:
    enabled: true
    serviceMonitor:
      additionalLabels:
        release: kps
      enabled: true
global:
  domain: argocd.k3s.lab
redis:
  metrics:
    enabled: true
    serviceMonitor:
      additionalLabels:
        release: kps
      enabled: true
repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      additionalLabels:
        release: kps
      enabled: true
server:
  extraArgs:
  - --insecure
  metrics:
    enabled: true
    serviceMonitor:
      additionalLabels:
        release: kps
      enabled: true
  service:
    type: ClusterIP
